python run.py with swell_frank_wolfe kappa=16 batch_size=128
python run.py with swell_frank_wolfe kappa=64 batch_size=128
python run.py with swell_frank_wolfe kappa=256 batch_size=128
python run.py with swell_frank_wolfe kappa=512 batch_size=128
python run.py with swell_frank_wolfe kappa=2048 batch_size=128
python run.py with swell_frank_wolfe kappa=4096 batch_size=128
python run.py with swell_frank_wolfe kappa=8192 batch_size=128
python run.py with swell_frank_wolfe kappa=16 batch_size=64
python run.py with swell_frank_wolfe kappa=64 batch_size=64
python run.py with swell_frank_wolfe kappa=256 batch_size=64
python run.py with swell_frank_wolfe kappa=512 batch_size=64
python run.py with swell_frank_wolfe kappa=2048 batch_size=64
python run.py with swell_frank_wolfe kappa=4096 batch_size=64
python run.py with swell_frank_wolfe kappa=8192 batch_size=64
python run.py with swell_frank_wolfe kappa=16 batch_size=256
python run.py with swell_frank_wolfe kappa=64 batch_size=256
python run.py with swell_frank_wolfe kappa=256 batch_size=256
python run.py with swell_frank_wolfe kappa=512 batch_size=256
python run.py with swell_frank_wolfe kappa=2048 batch_size=256
python run.py with swell_frank_wolfe kappa=4096 batch_size=256
python run.py with swell_frank_wolfe kappa=8192 batch_size=256